### ISSUE TITLE
NextJs build error - Module not found: Default condition should be last one

### ISSUE THREAD

**Issue by bclayton21** [micahjon/rhf-conditional-logic#1]
- NextJs: 14.2.3
- React Hook Form: 7.51.5
- Zod: 3.23.8

Using the following import method within a component:
`import { useConditionalForm } from 'rhf-conditional-logic';`

Getting the following error when running `next build`:
Module not found: Default condition should be last one

**Comment by micahjon** [comment]
Hey, thanks for reporting this--I was able to replicate and am looking into it. I'm guessing it has to do with how the files are packaged for npm.

**Comment by micahjon** [comment]
@bclayton21 , this should be fixed in version 0.1.1. Turns I just had to tweak my package.json file. Thanks for reporting, and let me know if any part of this library could be better!
